# Site settings
title: Mobile Development Group, IIT Roorkee
email: sdsmobilelabs@gmail.com
description: Where ideas meet reality

url: "http://mdg.iitr.ac.in/" # the base hostname & protocol for your site
asset_add: /assets/

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 
google_analytics: 
addthis_id: 
disqus_account: mdg-sdslabs-co

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/sdsmdg
  - title: facebook
    url: https://facebook.com/mdgiitr
  - title: google-plus
    url: https://plus.google.com/u/0/105615084243375129004
  - title: github
    url: https://github.com/sdsmdg
  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
# Build settings
